// profile sce_fp_psp2

#define POSTPROCESSING_ENABLED
#define _ANDROID
#define DESATURATION
#define DIFFUSE_TEXTURE



#ifdef DIFFUSE_TEXTURE
	uniform sampler2D Texture0;
#endif

void main(
	float2 uv0Varying : TEXCOORD0,
	float4 colorVarying : COLOR,
	float4 out gl_FragColor : COLOR
) {
#ifdef DIFFUSE_TEXTURE
	float4 color=tex2D(Texture0,uv0Varying);
#else
	float4 color=float4(1.0,1.0,1.0,1.0);
#endif

    color*=colorVarying;
	gl_FragColor=color;
}
