// profile sce_vp_psp2

#define _ANDROID



uniform float4x4 ModelViewMatrix;
uniform float4x4 ModelViewProjMatrix;
uniform float4 MappingScale;
uniform float4 MappingOffset;

void main(
	float3 Position,
	float2 UV0,
	float4 UV1,
	float4 out colorVarying : COLOR,
	float2 out uv0Varying : TEXCOORD0,
	float4 out gl_Position : POSITION
) {
	float3 pos=Position;
    gl_Position = mul(float4(pos,1),ModelViewProjMatrix);
    colorVarying = UV1;
	uv0Varying = UV0*MappingScale.xy+MappingOffset.xy;
}
